### ISSUE TITLE
Can you check the Sports and Broncos newsletter bugs?

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#1]
When we run the auto-producer and select the option to add a newsletter bug at the end of the story, no matter which option we pick, it adds the bug for the Mile High Roundup. 

Can you update it to have the Sports headlines newsletter or Broncos Insider as options when we select those?

Thanks!

**Comment by schneidan** [comment]
This was actually an issue with the Mailer Rules app that provides the content of that iframe -- but it's fixed now. Thanks for letting me know!
