### ISSUE TITLE
Add Preps stats sidebar to Preps stories

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#10]
Hello,

Can you please add this bit of code 4 graphs into all (96) Preps stories?

`<aside class='related right'> <h2 class='widget-title'><a href='http://preps.denverpost.com/'>Colorado Prep Stats</a></h2> [dfm_iframe src='http://preps.denverpost.com/sidebar.html' width='300px' height='250px' scrolling='no'] </aside>`

Thanks!

**Comment by schneidan** [comment]
This will be in today's release.
