### ISSUE TITLE
A request for a couple sports tweaks

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#11]
Can you change the embedded related articles link to default to keep the article dates off for all sports stories?

`[related_articles location="right" show_article_date="false" article_type="automatic-primary-tag"]`

Also, can you double-check that the MLB auto-producer command is adding in the SendToNews smart player after the fourth graph? 

`https://embed.sendtonews.com/oembed/?fk=5vyDixL5&amp;cid=5163&amp;sound=off&amp;format=json&amp;offsetx=0&amp;offsety=0&amp;floatwidth=400&amp;floatposition=bottom-right&amp;float=on`

**Comment by schneidan** [comment]
These issues should be fixed now.
