### ISSUE TITLE
Please have the Rockies autoproducer add this oembed link to the body

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#5]
Hello, can you please have the Autoproducer add this oembed link to the body copy of all Rockies stories?

http://embed.sendtonews.com/oembed/?fk=5vyDixL5&cid=5163&sound=off&format=json&offsetx=0&offsety=0&floatwidth=400&floatposition=bottom-right&float=on

I'm thinking 4 graphs in should work best.

Thanks,

**Comment by schneidan** [comment]
4 grafs in will conflict with related (if selected) and with embedded ads. I recommend either going at the top, or 8 grafs in.

**Comment by danielboniface** [comment]
Can we go 4 graphs in for the video player and 8 graphs in for the related links?

**Comment by schneidan** [comment]
that would involved rewriting related placement for everything. How about I just have it go in 4 grafs down and you guys can adjust it when needed, and if it conflicts too often we'll revisit.

**Comment by schneidan** [comment]
This should be in -- let me know how it works out for you.
