### ISSUE TITLE
Sports app downloads

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#6]
Hello, can you make the App download promo direct users to the Sports app on all sports stories?

Thanks,

**Comment by schneidan** [comment]
@danielboniface Yeah, I think I can make this happen ... I need the app logo, the text you want (if different), and the app store/Google Play store links. @ericjlubbers may have that stuff?

**Comment by danielboniface** [comment]
https://itunes.apple.com/us/app/denver-post-sports/id390951038?mt=8
https://play.google.com/store/apps/details?id=com.rumble.denver_post_sports&hl=en

**Comment by danielboniface** [comment]
![denver-post-sports-icon](https://user-images.githubusercontent.com/9724494/30172872-37434bbe-93b3-11e7-81d0-e0cb06ba00a0.png)

**Comment by schneidan** [comment]
@ericjlubbers Do you have the actual app icon version of this ^^ somewhere?

**Comment by danielboniface** [comment]
@schneidan I asked @ericjlubbers for the app icon and that's what he sent me.

**Comment by schneidan** [comment]
Ah, okay. I'll need to ease the corners then, I guess.

**Comment by ericjlubbers** [comment]
![dp-sports-app-small](https://user-images.githubusercontent.com/224754/30184334-0abc9500-93db-11e7-96b5-bb8d98c7ea46.png)

Finally. Suddenly forgot how to crop corners in the new-fangled version of Photoshop. @danielboniface @schneidan

**Comment by schneidan** [comment]
This is done.
