### ISSUE TITLE
Please add this SendToNews smart player oembed to the following AP commands

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#8]
Hello, 

Can you please add this SendToNews smart player oembed to the following Auto-Producer commands? I would like it to be inserted after 4 graphs. Please move the related stories tag to after 8 graphs. In addition, please add the "Outstream" feature tag to these stories.

`https://embed.sendtonews.com/oembed/?fk=5vyDixL5&amp;cid=5163&amp;sound=off&amp;format=json&amp;offsetx=0&amp;offsety=0&amp;floatwidth=400&amp;floatposition=bottom-right&amp;float=on`

(71) Broncos Story
(73) Nuggets Story
(74) Avalanche Story
(76) Golf Story
(77) NASCAR Story
(80) CU Buffs Football
(90) NFL Wire Story
(91) NBA Wire Story
(93) NHL Wire Story
(94) College Hoops Wire Story
(111) College Football Story

Thank you!

**Comment by schneidan** [comment]
This will be in today's release.
