### ISSUE TITLE
Add newsletter signups to Preps and Rockies

### ISSUE THREAD

**Issue by danielboniface** [denverpost/autoproducer#9]
Hello,

Can you please swap the Sports newsletter signup on these:

(96) Preps > Make this one a signup for the Prep Tally newsletter
(72) Rockies > Make this one a signup for the Rockies Insider newsletter
(92) MLB > Make this one a signup for the Rockies Insider newsletter

Thank you!

**Comment by schneidan** [comment]
I'm not away of the Prep Tally newsletter ...

**Comment by schneidan** [comment]
Alright, this is sorted and should appear shortly.
